language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-26
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-26
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-android-support
  - extra-google-m2repository
  - addon-google_apis-google-26
  - sys-img-armeabi-v7a-addon-google_apis-google-26
before_script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - echo no | android create avd --force -n test -t android-26 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck
after_success:
  - bash <(curl -s https://codecov.io/bash)
